<?php

namespace AppBundle\Repository;

/**
 * eventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventoRepository extends \Doctrine\ORM\EntityRepository
{
}
