<?php

namespace AppBundle\Repository;

/**
 * tipo_eventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tipo_eventoRepository extends \Doctrine\ORM\EntityRepository
{
}
